# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eleanor Graham
email: eleanorcjkgraham@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm learning things. You can join me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://eleanorgraham.com" # the base hostname & protocol for your site
permalink: /:categories/:title/
github_username:  eleanorgraham

# Build settings
markdown: kramdown


links:
- text: Welcome!
  url: /welcome/
  position: top
- text: Tags
  url: /tags/
  position: top
